/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Given an array of n integers, sort them in non-increasing order using MERGE SORT.
	For each merge() function call, print the arrays to be merged
		and the total number of comparisons performed, as shown in the execution example.
	Also, print the total number of comparisons performed throughout the sorting process.
 * Instructions:
	Complete the function/s
		mergeSort()
		merge()
	in the file sorting.c.
 * Execution Example/s:
	~Example 1
		Enter the number of elements: 10
		Enter 10 elements: 9 3 4 2 8 2 2 9 3 8
		[9]
		[3]
		1
		[2]
		[8]
		1
		[4]
		[2 8]
		2
		[3 9]
		[2 4 8]
		4
		[2]
		[2]
		1
		[3]
		[8]
		1
		[9]
		[3 8]
		2
		[2 2]
		[3 8 9]
		2
		[2 3 4 8 9]
		[2 2 3 8 9]
		9

		Sorted Array: [2 2 2 3 3 4 8 8 9 9]
		Total number of comparisons: 23

 	~Example 2
		Enter the number of elements: 16
		Enter 16 elements: 1 9 5 13 3 11 7 15 4 12 8 16 2 10 6 14
		[1]
		[9]
		1
		[5]
		[13]
		1
		[1 9]
		[5 13]
		3
		[3]
		[11]
		1
		[7]
		[15]
		1
		[3 11]
		[7 15]
		3
		[1 5 9 13]
		[3 7 11 15]
		7
		[4]
		[12]
		1
		[8]
		[16]
		1
		[4 12]
		[8 16]
		3
		[2]
		[10]
		1
		[6]
		[14]
		1
		[2 10]
		[6 14]
		3
		[4 8 12 16]
		[2 6 10 14]
		7
		[1 3 5 7 9 11 13 15]
		[2 4 6 8 10 12 14 16]
		15

		Sorted Array: [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16]
		Total number of comparisons: 49
	
*/

#include <stdio.h>
#include <stdlib.h>

#include "sorting.h"
#include "structure.h"

int comparisons = 0;
int binarySearchCount = 0;

int main()
{
	int n;

	printf("Enter the number of elements: ");
	scanf("%d%*c", &n);

	int* A = malloc(n * sizeof(int));

	printf("Enter %d elements: ", n);
	readArray(A, n);

	mergeSort(A, n);

	printf("\nSorted Array: ");
	printArray(A,n);

	printf("Total number of comparisons: %d\n", comparisons);

	return 0;
}
