/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Given an array of n integers, sort them in non-increasing order using QUICK SORT.
	For each quickSort() call, print the pivot, the index of pivot after partition, 
		and the two partitions as shown in the execution example.
	Also, print the total number of comparisons performed throughout the sorting process.
 * Instructions:
	Complete the function/s
		quickSort()
		recPartition()
	in the file sorting.c.
 * Execution Example/s:
	Enter the number of elements: 10
	Enter 10 elements: 40 20 70 10 50 80 90 25 60 35
	35 3
	[25 20 10]
	[50 80 90 70 60 40]
	10 0
	[20 25]
	25 1
	[20]
	40 0
	[80 90 70 60 50]
	50 0
	[90 70 60 80]
	80 2
	[60 70]
	[90]
	70 1
	[60]

	Sorted Array: [10 20 25 35 40 50 60 70 80 90]
	Total number of comparisons: 25
	
*/

#include <stdio.h>
#include <stdlib.h>

#include "sorting.h"
#include "structure.h"

int comparisons = 0;
int binarySearchCount = 0;

int main()
{
	int n;

	printf("Enter the number of elements: ");
	scanf("%d%*c", &n);

	int* A = malloc(n * sizeof(int));

	printf("Enter %d elements: ", n);
	readArray(A, n);

	quickSort(A, n);

	printf("\nSorted Array: ");
	printArray(A,n);

	printf("Total number of comparisons: %d\n", comparisons);

	return 0;
}
