/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	In this question, we are going to implement a hybrid sorting algorithm.
	Given an array of n integers, sort them in non-increasing order as follows.
		If n is a power of 2, sort the array using MERGE SORT.
		Otherwise, 
			Find m, the largest power of 2 which is less than n.
			Sort the first m elements in the array using MERGE SORT.
			Sort the remaining elements in the array using SELECTION SORT.
			Merge the two sorted sub-arrays A[0..m] and A[m+1..n] to get the sorted array.
	Also, print the total number of comparisons performed throughout the sorting process.
 * Instructions:
	Complete the function/s
		hybridSort()
		minIndex()
		selectionSort()
		merge()
		mergeSort()
	in the file sorting.c.
 * Execution Example/s:
		Enter the number of elements: 14
		Enter 14 elements: 9 2 6 1 7 3 1 7 9 6 8 4 3 2
		[9]
		[2]
		1
		[6]
		[1]
		1
		[2 9]
		[1 6]
		3
		[7]
		[3]
		1
		[1]
		[7]
		1
		[3 7]
		[1 7]
		3
		[1 2 6 9]
		[1 3 7 7]
		7
		[1 1 2 3 6 7 7 9]
		[2 3 4 6 8 9]
		13

		Sorted Array: [1 1 2 2 3 3 4 6 6 7 7 8 9 9]
		Total number of comparisons (including mergeSort and selectionSort): 45
*/

#include <stdio.h>
#include <stdlib.h>

#include "sorting.h"
#include "structure.h"

int comparisons = 0;
int binarySearchCount = 0;

int main()
{
	int n;

	printf("Enter the number of elements: ");
	scanf("%d%*c", &n);

	int* A = malloc(n * sizeof(int));

	printf("Enter %d elements: ", n);
	readArray(A, n);

	hybridSort(A, n);

	printf("\nSorted Array: ");
	printArray(A,n);

	printf("Total number of comparisons (including mergeSort and selectionSort): %d\n", comparisons);

	return 0;
}
