/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read the details of n movies and store them in the array.
	Use the structure 'movieArray' defined in structure.h.
	Sort the movies in the alphabetic order of their title using INSERTION SORT.
	If two movies have the same title, 
		they should be placed in the sorted array
		in the decreasing order of their average rating.
		If their average ratings is also the same, 
		they should be placed in the same order in the sorted array 
		as they appeared in the input.
	Print the movie details in the sorted array of structures.
 * Instructions:
	Complete the function/s
		insertMovie()
		movieInsertionSort()
	in the file sorting.c.
 * Execution Example/s:
		Enter the number of movies: 5

		Enter the movie details:

		Movie 1:
		Title: Avatar
		Release date (dd-mmm-yyyy): 21-aug-2000
		Number of ratings: 5
		Enter 5 ratings, separated by space.
		9 8 7.8 7.0 9

		Movie 2:
		Title: The Car
		Release date (dd-mmm-yyyy): 30-jun-2010
		Number of ratings: 4
		Enter 4 ratings, separated by space.
		9.4 8.5 4.5 8

		Movie 3:
		Title: Frozen
		Release date (dd-mmm-yyyy): 20-apr-2018
		Number of ratings: 5
		Enter 5 ratings, separated by space.
		9.3 4 6.7 9.9 8

		Movie 4:
		Title: Avatar
		Release date (dd-mmm-yyyy): 12-jan-2008
		Number of ratings: 4
		Enter 4 ratings, separated by space.
		9 9.4 9.5 9.6

		Movie 5:
		Title: The Car
		Release date (dd-mmm-yyyy): 13-nov-2002
		Number of ratings: 3
		Enter 3 ratings, separated by space.
		8.9 9.8 9

		Sorted Details:
		-----------------------------------------------
		|Rating |Release Date   |Title
		-----------------------------------------------
		|9.38   |12/01/2008     |Avatar
		|8.16   |21/08/2000     |Avatar
		|7.58   |20/04/2018     |Frozen
		|9.23   |13/11/2002     |The Car
		|7.60   |30/06/2010     |The Car
		-----------------------------------------------

*/

#include <stdio.h>

#include "structure.h"
#include "sorting.h"

int comparisons = 0;
int binarySearchCount = 0;

int main()
{
	int n;

	printf("Enter the number of movies: ");
	scanf("%d%*c", &n);
	
	movieArray* M = createMovieArray(n);
	printf("\nEnter the movie details:\n");
	readMovieArray(M);

	movieInsertionSort(M);

	printf("\nSorted Details:\n");
	printf("-----------------------------------------------\n");
	printMovieArray(M);

	
	return 0;
}
