/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read the details of n movies and store them in the array.
	Use the structure 'movieArray' defined in structure.h.
	Sort the movies based on their release date using SELECTION SORT.
	If two movies have the same release date,  
		they should be placed in the sorted array
		in the alphabetic order of their title.
	In this question, you can assume that the movie titles are unique.
	Print the movie details in the stored array of structures.
 * Instructions:
	Complete the function/s
		
	in the file sorting.c.
 * Execution Example/s:
		Enter the number of movies: 5

		Enter the movie details:

		Movie 1:
		Title: Avatar
		Release date (dd-mmm-yyyy): 21-may-2000
		Number of ratings: 3
		Enter 3 ratings, separated by space.
		9 4 7

		Movie 2:
		Title: The Car
		Release date (dd-mmm-yyyy): 20-apr-1989
		Number of ratings: 4
		Enter 4 ratings, separated by space.
		8 7 9.7 8.9

		Movie 3:
		Title: Frozen
		Release date (dd-mmm-yyyy): 23-jan-2008
		Number of ratings: 3
		Enter 3 ratings, separated by space.
		9.8 6.7 5.9

		Movie 4:
		Title: Iron Man
		Release date (dd-mmm-yyyy): 20-apr-2008
		Number of ratings: 5
		Enter 5 ratings, separated by space.
		9.5 7.3 6.5 8 4.5

		Movie 5:
		Title: Spider Man
		Release date (dd-mmm-yyyy): 20-apr-1989
		Number of ratings: 3
		Enter 3 ratings, separated by space.
		9 8 7

		Sorted Details:
		-----------------------------------------------
		|Rating |Release Date   |Title
		-----------------------------------------------
		|8.00   |20/04/1989     |Spider Man
		|8.40   |20/04/1989     |The Car
		|6.67   |21/05/2000     |Avatar
		|7.47   |23/01/2008     |Frozen
		|7.16   |20/04/2008     |Iron Man
		-----------------------------------------------
*/

#include <stdio.h>

#include "structure.h"
#include "sorting.h"

int comparisons = 0;
int binarySearchCount = 0;

int main()
{
	int n;

	printf("Enter the number of movies: ");
	scanf("%d%*c", &n);
	
	movieArray* M = createMovieArray(n);
	printf("\nEnter the movie details:\n");
	readMovieArray(M);

	movieSelectionSort(M);

	printf("\nSorted Details:\n");
	printf("-----------------------------------------------\n");
	printMovieArray(M);
	
	return 0;
}
