/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************
*/

#ifndef STRUCTURE_H
#define STRUCTURE_H

typedef struct {
    int day;
    int month;
    int year;
} date;


typedef struct {
    float* start;
    int size;
} ratingArray;


typedef struct {
    char* title;
    date releaseDate;
    ratingArray* ratings;
    float avgRating;
} movie;


typedef struct {
    movie* start;
    int size;
} movieArray;


extern void readArray(int*, int);

extern void printArray(int*, int);

extern date getDate();

extern void printDate(date);

extern ratingArray* createRatingArray(int n);

extern void readRatingArray(ratingArray*);

extern movie* createMovie();

extern void readMovie(movie*);

extern void printMovie(movie*);

extern float averageRating(movie*);

extern void swapMovies(movie*, movie*);

extern movieArray* createMovieArray(int);

extern void readMovieArray(movieArray*);

extern void printMovieArray(movieArray*);

#endif
