/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read an integer n where n > 1.
	Check whether n is a prime number or not.
 * Instructions:
	Complete the function/s
		isPrime()
	in the file prime.c. 
 * Execution Example/s:
	~ Example 1:
		Enter the number: 7
		7 is a prime number.
	~ Example 2:
		Enter the number: 4
		4 is not a prime number.
*/

#include <stdio.h>

#include "prime.h"

int main() {
	int n;

	printf("Enter the number: ");
	scanf("%d", &n);

	if (isPrime(n)) {
		printf("%d is a prime number.\n", n);
	} else {
		printf("%d is not a prime number.\n", n);
	}

	return 0;
}
