/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read an integer n where n > 1.
	Print all the prime numbers less than or equal to n, in ascending order.
 * Instructions:
	Complete the function/s
		printPrimes()
	in the file prime.c.
 * Execution Example/s:
	Enter the limit: 10
	The prime numbers <= 10 are 2 3 5 7 
*/

#include <stdio.h>

#include "prime.h"

int main() {
	int n;

	printf("Enter the limit: ");
	scanf("%d", &n);

	printPrimes(n);

	return 0;
}
