/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************
*/

/** 
	A function to check whether a given number is prime or not.
	@param n the number to check for prime or not
	@return 1, if n is prime
			0, otherwise
*/
extern int isPrime(int n);

/** 
	A function to print all the prime numbers less than or equal to n.
	@param n limit upto which the prime numbers are to be printed
	@example For n = 10, print the following (without quotes):
		"The prime numbers <= 10 are 2 3 5 7 "
*/
extern void printPrimes(int n);
