/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read a string of maximum length 1000, containing only letters, space and full stop. 
    Read a word w of maximum length 20,
        and find the number of occurrences of the word w in the string.
 * Instructions:
	Complete the function/s
		readString()
		countWord()
	in the file array.c.
 * Execution Example/s:
    ~Examaple 1
        Enter your string:
        India is my country. All Indians are my brothers and sisters.
        Enter the word: my
        'my' appears 2 times in the string.
    ~Examaple 2
        Enter your string:
        My father is my teacher and my friend.
        Enter the word: my
        'my' appears 2 times in the string.
    ~Examaple 3
        Enter your string:
        My father is my teacher and my friend. A friend in need is a friend indeed. 
        Enter the word: friend
        'friend' appears 3 times in the string.
    ~Examaple 4
        Enter your string: 
        My father is my teacher and my friend. A friend in need is a friend indeed. 
        Enter the word: end
        'end' appears 0 times in the string.
    ~Examaple 5
        Enter your string: 
        xyz abc abcd abcabc abcde 
        Enter the word: abc
        'abc' appears 1 times in the string.
*/

#include <stdio.h>

#include "array.h"

int main()
{
    char* str;
    char *w;

    printf("Enter your string:\n");
    str = readString(1000);

    printf("Enter the word: ");
    w = readString(20);

    int count = countWord(str, w);
    printf("'%s' appears %d times in the string.\n", w, count);

	return 0;
}
