/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read n distinct integers and store them in an array.
	Swap the first element with the smallest element in the array,
		and print the elements in the modified array.
 * Instructions:
	Complete the function/s
		initArray()
		readArray()
		minIndex()
		modifyArray()
		printArray()
	in the file array.c.
 * Execution Example/s:
	Enter the size of the array: 9
	Enter 9 elements:
	12 15 4 8 9 3 14 10 11
	The modified array is:
	3 15 4 8 9 12 14 10 11 
*/
#include <stdio.h>

#include "array.h"

int main()
{
	int n;
	int* A;

	printf("Enter the size of the array: ");
	scanf("%d", &n);

	A = initArray(n);

	printf("Enter %d elements:\n", n);
	readArray(A, n);

	modifyArray(A, n);

	printf("The modified array is: \n");
	printArray(A, n);

	return 0;
}
