/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Create an array A of size n.
	Initially all the locations in the array A are empty.
	Repeatedly read a positive integer p and perform the following steps, until p = -1.
		^ Find i = p mod n.
		^ If index i is empty in the array A, then store p at index i in A.
		^ Otherwise, add p to the current value present at index i in A.
	Finally, print the array A.
 * Instructions:
	Complete the function/s
		initArray()
		setArray()
		printArray()
	in the file array.c.
 * Execution Example/s:
	Enter the size of the array: 7
	Enter the elements (enter -1 to stop):
	12 8 5 24 29 2 41 31 17 20 -1
	The array is:
	-1 37 2 72 -1 17 61
*/
#include <stdio.h>

#include "array.h"

int main()
{
	int n, p;
	int* A;

	printf("Enter the size of the array: ");
	scanf("%d", &n);

	A = initArray(n);

	printf("Enter the elements (enter -1 to stop):\n");

	setArray(A, n);

	printf("The array is: \n");
	printArray(A, n);

	return 0;
}
