/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Definition/s:
	^ For an element at index i of an array, we define its neighbors as
		the elements at indices i-1 and i+1 of the array (if they exist).
	^ When an element A[i] is deleted,
		all the elements in the sub-array A[i+1..n-1] gets shifted once to the left,
		and the array size decreases by 1.
 * Question:
	Read n distinct integers and store them in an array A.
	The program then proceeds in rounds; in each round, perform the following operations.
		^ For each element a in the array A in order,
			if a is greater than all of its neighbors, then delete a from A.
		^ Print the array elements. 
	Repeat this process until
		no more elements are deleted from the array during a round.
 * Instructions:
	Complete the function/s
		initArray()
		readArray()
		shrinkArray()
	in the file array.c.
 * Execution Example/s:
	Enter the size of the array: 10
	Enter 10 elements:
	12 15 24 8 29 9 4 20 31 27
	12 15 8 4 20
	12 8 4
	4
	4
*/
#include <stdio.h>

#include "array.h"

int main()
{
	int n;
	int* A;

	printf("Enter the size of the array: ");
	scanf("%d", &n);

	A = initArray(n);

	printf("Enter %d elements:\n", n);
	readArray(A, n);

	shrinkArray(A, n);

	return 0;
}
