/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read n distinct integers and store them in an array A.
	Then, read one more integer and store it in p.
	Assume that p is present in A.
	Now, rearrange the elements in A such that the following conditions are satisfied.
		^ All the elements to the left of p are less than p, 
			and in the order in which they appeared in the input.
		^ All the elements to the right of p are greater than p, 
			and in the order in which they appeared in the input.
	(There are various ways in which this rearrangement can be performed;
		how exactly to do it is left as your choice.)
	Finally, print the rearranged array A.
 * Instructions:
	Complete the function/s
		initArray()
		readArray()
		arrangeArray()
		printArray()
	in the file array.c.
 * Execution Example/s:
	Enter the size of the array: 10
	Enter 10 elements:
	12 5 24 8 29 2 41 20 17 31
	Enter the element based on which the array is to be rearranged: 17
	The rearranged array is:
	12 5 8 2 17 24 29 41 20 31
*/
#include <stdio.h>

#include "array.h"

int main()
{
	int n, p, i;
	int* A;

	printf("Enter the size of the array: ");
	scanf("%d", &n);

	A = initArray(n);

	printf("Enter %d elements:\n", n);
	readArray(A, n);

	printf("Enter the element based on which the array is to be rearranged: ");
	scanf("%d", &p);

	arrangeArray(A, n, p);

	printf("The rearranged array is: \n");
	printArray(A, n);

	return 0;
}
