/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read n integers, sorted in ascending order, and store them in an array A.
	Again, read m integers, sorted in ascending order, and store them in an array B.
	Now, create an empty array C of size n+m,
		and populate it with all the elements in A and B, sorted in descending order,
		as described below:
		^ Let the largest elements in A and B which are not yet added to C be a and b, respectively.
		^ If a > b, set the first empty position in C to a and print the string "A ".
			Otherwise, set that position to b and print the string "B ".
		^ Repeat the previous steps until either A or B has no more elements to be added to C.
		^ At this point one of the arrays A or B will contain elements that have not been added to C;
			one-by-one, add these elements to C in descending order.
	Finally, print the array C.
 * Instructions:
	Complete the function/s
		initArray()
		readArray()
		combineArray()
		printArray()
	in the file array.c.
 * Execution Example/s:
	Enter the size of the first array: 7
	Enter 7 elements of array A:
	2 8 17 24 29 32 41
	Enter the size of the second array: 5
	Enter 5 elements of array B:
	17 17 20 45 67
	B B A A A A B B B A A A
	The combined array is:
	67 45 41 32 29 24 20 17 17 17 8 2
*/
#include <stdio.h>

#include "array.h"

int main()
{
	int n, m;
	int* A;
	int* B;
	int* C;
	
	printf("Enter the size of the first array: ");
	scanf("%d", &n);
	A = initArray(n);
	printf("Enter %d elements of array A:\n", n);
	readArray(A, n);

	printf("Enter the size of the second array: ");
	scanf("%d", &m);
	B = initArray(m);
	printf("Enter %d elements of array B:\n", m);
	readArray(B, m);

	C = combineArray(A, n, B, m);

	printf("\nThe combined array is:\n");
	printArray(C, n+m);

	return 0;
}
