/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
    Amrita School of Artificial Intelligence is planning to conduct 
        an Arts and Literary competition this academic year. 
    A student can participate in more than one events.
    Given the list of roll numbers (integer) of students registered for English speech, 
        Hindi speech, and debate; perform the following tasks.
            ^ List the students registered for at least one of the speech events.
            ^ List the students registered only for debate.
 * Instructions:
	Complete the function/s
        readStudents()
        printStudents()
        speechStudents()
        debateStudents()
	in the file array.c.
 * Execution Example/s:
    ~ Example 1:
        Enter the number of students registered for English speech: 6
        Enter the roll number of 6 students registered for English speech:
        10 1 4 5 17 12
        Enter the number of students registered for Hindi speech: 7
        Enter the roll number of 7 students registered for Hindi speech:
        3 2 8 7 18 24 6
        Enter the number of students registered for debate: 9
        Enter the roll number of 9 students registered for debate:
        2 15 4 8 9 3 14 10 11
        Students registered for at least one of the speech events:
        10 1 4 5 17 12 3 2 8 7 18 24 6
        Students registered only for debate:
        15 9 14 11
    ~ Example 2: 
        Enter the number of students registered for English speech: 7
        Enter the roll number of 6 students registered for English speech:
        10 1 2 4 5 7 12
        Enter the number of students registered for Hindi speech: 8
        Enter the roll number of 7 students registered for Hindi speech:
        3 5 2 8 7 1 4 6
        Enter the number of students registered for debate: 5
        Enter the roll number of 9 students registered for debate:
        2 5 4 8 6
        Students registered for at least one of the speech events:
        10 1 2 4 5 7 12 3 8 6
        Students registered only for debate:
        -1
*/

#include <stdio.h>

#include "array.h"

int main()
{
    int n1, n2, n3;
    int* E;
    int* H;
    int* D;
    int* S;
    int* R;
    
    printf("Enter the number of students registered for English speech: ");
    scanf("%d", &n1);
    E = initArray(n1);
    printf("Enter the roll number of %d students registered for English speech:\n", n1);
    readStudents(E, n1);

    printf("Enter the number of students registered for Hindi speech: ");
    scanf("%d", &n2);
    H = initArray(n2);
    printf("Enter the roll number of %d students registered for Hindi speech:\n", n2);
    readStudents(H, n2);

    printf("Enter the number of students registered for debate: ");
    scanf("%d", &n3);
    D = initArray(n3);
    printf("Enter the roll number of %d students registered for debate:\n", n3);
    readStudents(D, n3);

    S = initArray(n1+n2);
    int s = speechStudents(E, n1, H, n2, S);
    printf("Students registered for at least one of the speech events: \n");
    printStudents(S, s);

    R = initArray(n3);
    int r = debateStudents(S, s, D, n3, R);
    printf("Students registered only for debate: \n");
    printStudents(R, r);

    return 0;
}