/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read a string of maximum length 1000. 
    Read a character ch and 
        find the number of occurrences of ch in the string.
 * Instructions:
	Complete the function/s
		readString()
		countChar()
	in the file array.c.
 * Execution Example/s:
    Enter your string:
    India is my country. All Indians are my brothers and sisters.
    Enter the character: a
    'a' appears 4 times in the string.
*/
#include <stdio.h>

#include "array.h"

int main()
{
    char* str;
    char ch;

    printf("Enter your string:\n");
    str = readString(1000);

    printf("Enter the character: ");
    scanf("%c", &ch);

    int count = countChar(str, ch);
    printf("'%c' appears %d times in the string.\n", ch, count);

	return 0;
}
