/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read the details of a movie and store them as a structure.
	For a movie, you need to read the title, year of release, and average rating.
	Use the structure 'movieQ1' defined in structure.h.
	Print the movie details stored in the structure.
 * Instructions:
	Complete the function/s
		createMovieQ1()
		readMovieQ1()
		printMovieQ1()
	in the file structure.c.
 * Execution Example/s:
	Enter the details of the movie as follows:
	 In the first line, give the title.
	 In the second line, give the year of release.
	 In the third line, give the average rating.
	My Movie
	2024
	9.8763

	Movie Details:
	--------------
	Title: My Movie, Year: 2024, Average Rating: 9.88
*/

#include <stdio.h>

#include "structure.h"

int main()
{
	movieQ1* m = createMovieQ1();

	printf("Enter the details of the movie as follows: \n");
	printf(" In the first line, give the title. \n");
	printf(" In the second line, give the year of release. \n");
	printf(" In the third line, give the average rating. \n");
	readMovieQ1(m);

	printf("\nMovie Details:\n");
	printf("--------------\n");
	printMovieQ1(m);

	return 0;
}
