/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	For a movie, instead of storing the average rating, 
		we are going to store all the ratings as an array.
	Read the details of a movie and store them as a structure.
	Use the structure 'movieQ2' defined in structure.h.
	Print the movie details stored in the structure.
	Also, find and print the average rating of the movie.
 * Instructions:
	Complete the function/s
		createMovieQ2()
		readMovieQ2()
		printMovieQ2()
		averageRating()
	in the file structure.c.
 * Execution Example/s:
	Enter the details of the movie as follows:
	 In the first line, give the title.
	 In the next line, give the year of release.
	 In the next line, give the value of r, which is the number of ratings.
	 In the next line, give r ratings, separated by space.
	My Movie
	2023
	4
	8.5 6.5 9 7.5

	Movie Details:
	--------------
	Title: My Movie, Year: 2023, Average Rating: 7.88
*/

#include <stdio.h>

#include "structure.h"

int main()
{
	movieQ2* m = createMovieQ2();

	printf("Enter the details of the movie as follows: \n");
	printf(" In the first line, give the title. \n");
	printf(" In the next line, give the year of release. \n");
	printf(" In the next line, give the value of r, which is the number of ratings. \n");
	printf(" In the next line, give r ratings, separated by space. \n");
	readMovieQ2(m);

	printf("\nMovie Details:\n");
	printf("--------------\n");
	printMovieQ2(m);

	printf("Average Rating: %.2f\n", averageRating(m));

	return 0;
}
