/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Given a date in the format dd-mmm-yyyy, 
		read it as a string and extract day, month and year. 
	Store the date as a structure 'date' given in structure.h. 
	Then check whether it is a valid date between the years 1900 and 2050 (both included).
 * Instructions:
	Complete the function/s
		getDate()
		printDate()
		isValidDate()
	in the file structure.c.
 * Execution Example/s:
	~Example 1:
		Enter the date in the format dd-mmm-yyyy: 29-feb-2004
		Date 29/02/2004 is valid.
	~Example 2: 
		Enter the date in the format dd-mmm-yyyy: 31-jun-1900
		Date 31/06/1900 is invalid.
*/

#include <stdio.h>

#include "structure.h"

int main()
{
	date myDate;

	printf("Enter the date in the format dd-mmm-yyyy: ");
	myDate = getDate();

	printf("Date ");
	printDate(myDate);
	printf(" is ");

	if(isValidDate(myDate)) {
		printf("valid.\n");
	}
	else {
		printf("invalid.\n");
	}

	return 0;
}
