/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Let us replace the 'year of release' in the movie details with 'date of release'.
	Use the structures 'movieQ4' and 'date' defined in structure.h.
	Print the movie details stored in the structure.
	A movie is eligible for an award nominations 
		if it was released on or before October. 
	Check whether the movie is eligible for nominations or not.
 * Instructions:
	Complete the function/s
		createMovieQ4()
		readMovieQ4()
		printMovieQ4()
		isEligible()
	in the file structure.c.
 * Execution Example/s:
	Enter the details of the movie as follows:
	 In the first line, give the title.
	 In the next line, give the release date in the format dd-mmm-yyyy.
	 In the next line, give the value of r, which is the number of ratings.
	 In the next line, give r ratings, separated by space.
	My Movie
	01-jun-2005
	5
	9 8.0 7.456 8.5 4.812

	Movie Details:
	--------------
	Title: My Movie, Release Date: 01/06/2005
	Ratings: 9.00 8.00 7.46 8.50 4.81 
	'My Movie' is eligible for nominations.
*/

#include <stdio.h>

#include "structure.h"

int main()
{
	movieQ4* m = createMovieQ4();

	printf("Enter the details of the movie as follows: \n");
	printf(" In the first line, give the title. \n");
	printf(" In the next line, give the release date in the format dd-mmm-yyyy. \n");
	printf(" In the next line, give the value of r, which is the number of ratings. \n");
	printf(" In the next line, give r ratings, separated by space. \n");
	readMovieQ4(m);

	printf("\nMovie Details:\n");
	printf("--------------\n");
	printMovieQ4(m);

	if(isEligible(m)) {
		printf("'%s' is eligible for nominations.\n", m->title);
	}
	else {
		printf("'%s' is not eligible for nominations.\n", m->title);
	}

	return 0;
}
