/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Along with a rating, let us store the username of the user who gave that rating.
	This information can be stored as a structure named 'rating'.
	Read the details of a movie and store them as a structure.
	Use the structures 'movieQ5' and 'rating' defined in structure.h.
	Print the movie details stored in the structure.
	Also, print the username of the user who gave the highest rating.
 * Instructions:
	Complete the function/s
		createMovieQ5()
		readMovieQ5()
		printMovieQ5()
		highestRatingUser()
	in the file structure.c.
 * Execution Example/s:
	Enter the details of the movie as follows:
	 In the first line, give the title.
	 In the next line, give the release date in the format dd-mmm-yyyy.
	 In the next line, give the value of r, which is the number of ratings.
	 In the next r lines, give r ratings as username and rating value, separated by space.
	My Movie
	13-oct-2015
	3
	user1 8.76
	user2 9
	user3 7.504

	Movie Details:
	--------------
	Title: My Movie, Release Date: 13/10/2015
	Ratings:
	user1 8.76
	user2 9.00
	user3 7.50
	Highest rating given by: user2
*/

#include <stdio.h>

#include "structure.h"

int main()
{
	movieQ5* m = createMovieQ5();

	printf("Enter the details of the movie as follows: \n");
	printf(" In the first line, give the title. \n");
	printf(" In the next line, give the release date in the format dd-mmm-yyyy. \n");
	printf(" In the next line, give the value of r, which is the number of ratings. \n");
	printf(" In the next r lines, give r ratings as username and rating value, separated by space. \n");
	readMovieQ5(m);

	printf("\nMovie Details:\n");
	printf("--------------\n");
	printMovieQ5(m);

	printf("Highest rating given by: %s\n", highestRatingUser(m));

	return 0;
}
