/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read n integers and store them in an array represented as a structure.
	Use the structure 'intArray' defined in structure.h.
	Print the values in the array.
 * Instructions:
	Complete the function/s
		createIntArray()
		readIntArray()
		printIntArray()
	in the file structure.c.
 * Execution Example/s:
	Enter the size of the array: 5
	Enter 5 elements: 34 6 432 89 9
	The array elements are: 34 6 432 89 9 
*/

#include <stdio.h>

#include "structure.h"

int main()
{
	int n;

	printf("Enter the size of the array: ");
	scanf("%d%*c", &n);

	intArray* A = createIntArray(n);

	printf("Enter %d elements: ", n);
	readIntArray(A);

	printf("The array elements are: ");
	printIntArray(A);

	return 0;
}
