/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Extending the concept of Question 6, let us store the ratings array as a structure.
	Read r ratings and store them in an array represented as a structure.
	Use the structure 'ratingArray' defined in structure.h.
	Print the ratings (username and rating value) in the array.
 * Instructions:
	Complete the function/s
		createRatingArray()
		readRatingArray()
		printRatingArray()
	in the file structure.c.
 * Execution Example/s:
	Enter the number of ratings: 5
	Enter 5 ratings (username and rating value in each line, separated by space):
	user1 7.90
	user2 8
	user3 9.876
	user4 4.5311
	user5 5.91

	Ratings:
	----------
	user1 7.90
	user2 8.00
	user3 9.88
	user4 4.53
	user5 5.91
*/

#include <stdio.h>

#include "structure.h"

int main()
{
	int r;

	printf("Enter the number of ratings: ");
	scanf("%d%*c", &r);
	
	ratingArray* R = createRatingArray(r);

	printf("Enter %d ratings (username and rating value in each line, separated by space):\n", r);
	readRatingArray(R);

	printf("\nRatings:\n");
	printf("----------\n");
	printRatingArray(R);

	return 0;
}
