/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Now let us create the final movie structure incorporating the rating array.
	Read the details of a movie and store it as a structure.
	Use the structure 'movie' defined in structure.h.
	Print the movie details stored in the structure.
	Also, find and print the highest rating the movie received.
 * Instructions:
	Complete the function/s
		createMovie()
		readMovie()
		printMovie()
		highestRating()
	in the file structure.c.
 * Execution Example/s:
	Enter the details of the movie as follows:
	 In the first line, give the title.
	 In the next line, give the release date in the format dd-mmm-yyyy.
	 In the next line, give the value of r, which is the number of ratings.
	 In the next r lines, give r ratings as username and rating value, separated by space.
	My Movie
	25-aug-2020
	5
	user1 8.77
	user2 8.774
	user3 8.7761
	user4 8.7
	user5 8.7760

	Movie Details:
	--------------
	Title: My Movie, Release Date: 25/08/2020
	Ratings:
	user1 8.77
	user2 8.77
	user3 8.78
	user4 8.70
	user5 8.78
	Highest rating: 8.78 given by user3
*/

#include <stdio.h>

#include "structure.h"

int main()
{
	movie* m = createMovie();

	printf("Enter the details of the movie as follows: \n");
	printf(" In the first line, give the title. \n");
	printf(" In the next line, give the release date in the format dd-mmm-yyyy. \n");
	printf(" In the next line, give the value of r, which is the number of ratings. \n");
	printf(" In the next r lines, give r ratings as username and rating value, separated by space. \n");
	readMovie(m);

	printf("\nMovie Details:\n");
	printf("--------------\n");
	printMovie(m);

	rating* r = highestRating(m);
	printf("Highest rating: %.2f given by %s\n", r->value, r->username);

	return 0;
}
