/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************
*/

#ifndef STRUCTURE_H
#define STRUCTURE_H

typedef struct {
    char* title;
    int year;
    float avgRating;
} movieQ1;


typedef struct {
    char* title;
    int year;
    int ratingsCount;
    float* ratings;
} movieQ2;


typedef struct {
    int day;
    int month;
    int year;
} date;


typedef struct {
    char* title;
    date releaseDate;
    int ratingsCount;
    float* ratings;
} movieQ4;


typedef struct {
    char* username;
    float value;
} rating;


typedef struct {
    char* title;
    date releaseDate;
    int ratingsCount;
    rating* ratings;
} movieQ5;


typedef struct {
    int* start;
    int size;
} intArray;


typedef struct {
    rating* start;
    int size;
} ratingArray;


typedef struct {
    char* title;
    date releaseDate;
    ratingArray* ratings;
} movie;


typedef struct {
    movie* start;
    int size;
} movieArray;


typedef struct {
    movie** start;
    int size;
} moviePtrArray;


extern movieQ1* createMovieQ1();

extern void readMovieQ1(movieQ1*);

extern void printMovieQ1(movieQ1*);

extern movieQ2* createMovieQ2();

extern void readMovieQ2(movieQ2*);

extern void printMovieQ2(movieQ2*);

extern float averageRating(movieQ2*);

extern date getDate();

extern int isValidDate(date);

extern void printDate(date);

extern movieQ4* createMovieQ4();

extern void readMovieQ4(movieQ4*);

extern void printMovieQ4(movieQ4*);

extern int isEligible(movieQ4*);

extern movieQ5* createMovieQ5();

extern void readMovieQ5(movieQ5*);

extern void printMovieQ5(movieQ5*);

extern char* highestRatingUser(movieQ5*);

extern intArray* createIntArray(int);

extern void readIntArray(intArray*);

extern void printIntArray(intArray*);

extern ratingArray* createRatingArray(int n);

extern void readRatingArray(ratingArray*);

extern void printRatingArray(ratingArray*);

extern movie* createMovie();

extern void readMovie(movie*);

extern void printMovie(movie*);

extern rating* highestRating(movie*);

extern movieArray* createMovieArray(int);

extern void readMovieArray(movieArray*);

extern void printMovieArray(movieArray*);

extern void printMoviesAbove8(movieArray*);

extern moviePtrArray* createMoviePointerArray(int);

extern void readMoviePointerArray(moviePtrArray*);

extern void printMoviePointerArray(moviePtrArray*);

extern void printMoviesAfter2000(moviePtrArray*);

#endif
