/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read a string of maximum length 1000. 
    Read a character ch and 
        find the number of occurrences of ch in the string using RECURSION.
 * Instructions:
	Complete the function/s
		recCountChar()
	in the file function.c.
 * Execution Example/s:
    Enter your string:
    India is my country. All Indians are my brothers and sisters.
    Enter the character: a
    'a' appears 4 times in the string.
*/

#include <stdio.h>
#include <stdlib.h>

#include "function.h"

int main()
{
    char ch;
    char* str = (char*)malloc(1001 * sizeof(char));

    printf("Enter your string:\n");
    scanf("%[^\n]%*c", str);

    printf("Enter the character: ");
    scanf("%c%*c", &ch);

    int count = recCountChar(str, ch);
    printf("'%c' appears %d times in the string.\n", ch, count);

	return 0;
}
