/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read an array of n double values.  
    Find the index of the minimum element in the array using RECURSION.
	If the minimum element is present more than once in the array, 
		select the index of its first occurrence.
 * Instructions:
	Complete the function/s
		recMinIndex()
	in the file function.c.
 * Execution Example/s:
	Enter the size of the array: 9
	Enter 9 elements:
	12.3 15.23 4.12 8.234 9.34 3.78 14 3.78 11.0
	Index of the minimum element is: 5
*/

#include <stdio.h>
#include <stdlib.h>

#include "function.h"

int main()
{
	int n;
	
	printf("Enter the size of the array: ");
	scanf("%d%*c", &n);
	double* A = (double*)malloc(n * sizeof(double));

	printf("Enter %d elements:\n", n);
	for(int i = 0; i < n; i++) {
		scanf("%lf%*c", (A+i));
	}

	printf("Index of the minimum element is: %d\n", recMinIndex(A, n));

	return 0;
}
