/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read an array of n double values.  
    Find the index of the first occurrence of a given element in an array using RECURSION.
 * Instructions:
	Complete the function/s
		recFindIndex()
	in the file function.c.
 * Execution Example/s:
	Enter the size of the array: 9
	Enter 9 elements:
	12.3 15.23 4.12 8.234 9.34 3.78 14.0 10.1 14
	Enter the element: 14
	Index of 14.00 is 6
*/

#include <stdio.h>
#include <stdlib.h>

#include "function.h"

int main()
{
	int n;
	double value;
	
	printf("Enter the size of the array: ");
	scanf("%d%*c", &n);
	double* A = (double*)malloc(n * sizeof(double));

	printf("Enter %d elements:\n", n);
	for(int i = 0; i < n; i++) {
		scanf("%lf%*c", (A+i));
	}

	printf("Enter the element: ");
	scanf("%lf%*c", &value);

	int index  = recFindIndex(A, n, value);
	if(index == -1) {
		printf("%.2lf is not present in the array\n", value);
	}
	else{
		printf("Index of %.2lf is %d\n", value, index);
	}

	return 0;
}
