/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read an array A of n double values in which 
		the first n-1 elements A[0..n-2] are in non-decreasing order.  
    Place the nth element A[n-1] in the array A such that 
		the entire array is in non-decreasing order, using RECURSION.
 * Instructions:
	Complete the function/s
		swap()
		recInsert()
	in the file function.c.
 * Execution Example/s:
	Enter the size of the array: 9
	Enter 9 elements:
	2.3 4.23 4.62 8.234 9.34 9.34 14 14.1 7.0
	The modified array is:
	2.30 4.23 4.62 7.00 8.23 9.34 9.34 14.00 14.10 
*/

#include <stdio.h>
#include <stdlib.h>

#include "function.h"

int main()
{
	int n;
	
	printf("Enter the size of the array: ");
	scanf("%d%*c", &n);
	double* A = (double*)malloc(n * sizeof(double));

	printf("Enter %d elements:\n", n);
	for(int i = 0; i < n; i++) {
		scanf("%lf%*c", (A+i));
	}

	recInsert(A, n);
	
	printf("The modified array is:\n");
	for(int i = 0; i < n; i++) {
		printf("%.2lf ", *(A+i));
	}
	printf("\n");

	return 0;
}
