/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	Read an array of n double values.  
	Sort them using RECURSIVE SELECTION SORT.
 * Instructions:
	Complete the function/s
		swap()
		recMinIndex()
		recSelectionSort()
	in the file function.c.
 * Execution Example/s:
	Enter the size of the array: 10
	Enter 10 elements:
	12.0 5.34 20.400 8.3 29.346 2 41.6 20.4 17.67 31
	The sorted array is:
	2.00 5.34 8.30 12.00 17.67 20.40 20.40 29.35 31.00 41.60 
*/

#include <stdio.h>
#include <stdlib.h>

#include "function.h"

int main()
{
	int n;

	printf("Enter the size of the array: ");
	scanf("%d%*c", &n);

	double* A = (double*)malloc(n * sizeof(double));

	printf("Enter %d elements:\n", n);
	for(int i = 0; i < n; i++) {
		scanf("%lf%*c", (A+i));
	}
	
	recSelectionSort(A, n);
	
	printf("The sorted array is:\n");
	for(int i = 0; i < n; i++) {
		printf("%.2lf ", *(A+i));
	}
	printf("\n");
}
