/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************

 * Question:
	An array containing double values is defined by the structure,
		typedef struct {
			double* start;
			int length;
			int capacity;
		} doubleArray;
		where, start indicates the starting address of the array,
		length indicates the current size of the array and 
		capacity indicates the maximum possible size of the array. 
	Create an empty array and perform a series of 
		insert, delete and search operations in the array using commands
		as explained in the function definition of processArray() in function.c. 
 * Instructions:
	Complete the function/s
		createArray()
		insertAt()
		insertFirst()
		insertLast()
		insertBefore()
		deleteAt()
		deleteFirst()
		deleteLast()
		deleteValue()
		recFindIndex()
		printArray()
		processArray()
	in the file function.c.
 * Execution Example/s:
	Enter the capacity of the array: 5
	Enter the commands one by one:
	i f 10
	0
	i l 20
	1
	p
	10.00 20.00
	i a 1 30
	1
	p
	10.00 30.00 20.00
	i a 4 40
	3
	i b 50 90
	-1
	i b 10 50
	0
	p
	50.00 10.00 30.00 20.00 40.00
	f 20
	3
	f 60
	-1
	i a 4 60
	-1
	i f
	-1
	i l
	-1
	d f
	50.00
	p
	10.00 30.00 20.00 40.00
	i a 3 40
	3
	p
	10.00 30.00 20.00 40.00 40.00
	f 40
	3
	d v 50
	-1
	d a 1
	30.00
	i b 40 50
	2
	d l
	40.00
	p
	10.00 20.00 50.00 40.00
	d v 20
	20.00
	p
	10.00 50.00 40.00
	d f
	10.00
	d f
	50.00
	d a 3
	-1
	d v 40
	40.00
	p
	-1
	d l
	-1
	s
	
*/

#include <stdio.h>

#include "function.h"

int main()
{
	int n;
	doubleArray* A;

	printf("Enter the capacity of the array: ");
	scanf("%d%*c", &n);

	A = createArray(n);

	printf("Enter the commands one by one:\n");
	processArray(A);

	return 0;
}
