/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************
*/

typedef struct {
    double* start;
    int length;
    int capacity;
} doubleArray;

extern void swap(double*, double*);

extern int recCountChar(char*, char);

extern void recSelectionSort(double*, int);

extern void recInsertionSort(double*, int);

extern doubleArray* createArray(int);

extern void processArray(doubleArray*);

extern void printArray(doubleArray*);

extern int recFindIndex(double*, int, double);

extern void recInsert(double*, int);

extern int insertFirst(doubleArray*, double);

extern int insertLast(doubleArray*, double);

extern int insertAt(doubleArray*, int, double);

extern int insertBefore(doubleArray*, double, double);
 
extern double deleteFirst(doubleArray*);

extern double deleteLast(doubleArray*);

extern double deleteAt(doubleArray*, int);

extern double deleteValue(doubleArray*, double);
 
extern int recMinIndex(double*, int);
